CREATE TABLE IF NOT EXISTS "users" (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(500),
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(500) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);